/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.6
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"time"

	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
	api "middleland.net/swaggerapi/petstore"
)

func main() {

	// Define command-line flags
	serverAddr := os.Getenv("SERVER_ADDR")
	if serverAddr == "" {
		serverAddr = "localhost:8080"
	}

	mongoURI := os.Getenv("DATABASE_URI")
	if mongoURI == "" {
		mongoURI = "mongodb://localhost:27017"
	}
	mongoDatabase := os.Getenv("DATABASE_NAME")
	if mongoDatabase == "" {
		mongoDatabase = "petstore"
	}

	enableCredentialsEnv := os.Getenv("ENABLE_CREDENTIALS")
	enableCredentials := false
	if enableCredentialsEnv == "true" {
		enableCredentials = true
	}

	// Create logger for writing information and error messages.
	infoLog := log.New(os.Stdout, "INFO\t", log.Ldate|log.Ltime)
	errLog := log.New(os.Stderr, "ERROR\t", log.Ldate|log.Ltime|log.Lshortfile)

	// show mongoURI and mongoDatabase and enableCredentials
	infoLog.Printf("mongoURI: %s", mongoURI)
	infoLog.Printf("mongoDatabase: %s", mongoDatabase)
	infoLog.Printf("enableCredentials: %t", enableCredentials)

	// Create mongo client configuration
	co := options.Client().ApplyURI(mongoURI)
	if enableCredentials {
		co.Auth = &options.Credential{
			Username: os.Getenv("MONGODB_USERNAME"),
			Password: os.Getenv("MONGODB_PASSWORD"),
		}
	}

	// Establish database connection
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	client, err := mongo.Connect(ctx, co)
	if err != nil {
		errLog.Fatal(err)
	}

	defer func() {
		// Use a fresh context for disconnection
		disconnectCtx, disconnectCancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer disconnectCancel()
		if err = client.Disconnect(disconnectCtx); err != nil {
			errLog.Printf("Error disconnecting from MongoDB: %v", err)
		}
	}()

	infoLog.Printf("Database connection established")

	app := api.NewLog(
		infoLog,
		errLog,
		&api.PetModel{
			C: client.Database(mongoDatabase).Collection("pets"),
		},
		&api.StoreModel{
			C: client.Database(mongoDatabase).Collection("stores"),
		},
		&api.UserModel{
			C: client.Database(mongoDatabase).Collection("users"),
		},
	)

	// Initialize a new http.Server struct.
	srv := &http.Server{
		Addr:         serverAddr,
		ErrorLog:     errLog,
		Handler:      app.NewRouter(),
		IdleTimeout:  time.Minute,
		ReadTimeout:  5 * time.Second,
		WriteTimeout: 10 * time.Second,
	}

	infoLog.Printf("Starting server on %s", serverAddr)
	go func() {
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			errLog.Fatalf("Server failed to start: %v", err)
		}
	}()

	// Graceful shutdown
	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt)
	<-stop

	infoLog.Println("Shutting down server...")

	// Use a fresh context for shutdown
	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer shutdownCancel()

	if err := srv.Shutdown(shutdownCtx); err != nil {
		errLog.Fatalf("Server forced to shutdown: %v", err)
	}

	infoLog.Println("Server exiting")
}
