/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.6
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package petstore

import (
	"encoding/json"
	"fmt"
	"net/http"
	"reflect"
	"strconv"

	"github.com/gorilla/mux"
)

var Orders []Order

func (app *Application) DeleteOrder(w http.ResponseWriter, r *http.Request) {

	vars := mux.Vars(r)

	fmt.Printf("DeleteOrder::id is %s\n", vars["orderId"])
	id, err := strconv.ParseInt(vars["orderId"], 10, 32)
	if err != nil {
		app.ErrorResponse(w, http.StatusBadRequest, "Invalid order ID")
		return
	}

	for index, order := range Orders {
		if order.Id == id {
			Orders = append(Orders[:index], Orders[index+1:]...)
		}
	}

	app.WriteJSON(w, http.StatusOK, map[string]string{"status": "deleted"})
}

func (app *Application) GetInventory(w http.ResponseWriter, r *http.Request) {

	fmt.Println("GetInventory:: return all orders")
	app.WriteJSON(w, http.StatusOK, Orders)
}

func (app *Application) GetOrderById(w http.ResponseWriter, r *http.Request) {
	var result Order
	vars := mux.Vars(r)

	id, err := strconv.ParseInt(vars["orderId"], 10, 32)
	if err != nil {
		app.ErrorResponse(w, http.StatusBadRequest, "Invalid order ID")
		return
	}
	fmt.Printf("GetOrderById id: %d\n", id)

	for _, order := range Orders {
		if order.Id == id {
			result = order
		}
	}

	if reflect.ValueOf(result).IsZero() {
		app.ErrorResponse(w, http.StatusNotFound, "Order not found")
	} else {
		app.WriteJSON(w, http.StatusOK, result)
	}
}

func (app *Application) PlaceOrder(w http.ResponseWriter, r *http.Request) {

	var order Order
	err := json.NewDecoder(r.Body).Decode(&order)
	if err != nil {
		app.ErrorResponse(w, http.StatusBadRequest, "Invalid request body")
		return
	}

	// update our global Pets array to include
	// our new Pet
	Orders = append(Orders, order)
	app.WriteJSON(w, http.StatusOK, order)
}
