/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.6
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package petstore

import (
	"encoding/json"
	"errors"
	"net/http"
	"reflect"
	"strings"

	"github.com/gorilla/mux"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

func (app *Application) AddPet(w http.ResponseWriter, r *http.Request) {

	if r.Method == "OPTIONS" {
		app.enableCors(w, r)
		w.WriteHeader(http.StatusOK)
		return
	}
	// Define Pets model
	var m Pet
	// Get request information
	err := json.NewDecoder(r.Body).Decode(&m)
	if err != nil {
		app.serverError(w, err)
		return
	}

	// Insert new Pets
	insertResult, err := app.pets.Insert(r.Context(), m)
	if err != nil {
		app.serverError(w, err)
		return
	}
	m.ID = insertResult.InsertedID.(primitive.ObjectID)

	app.infoLog.Printf("New pet have been created, id=%s", insertResult.InsertedID)
	w.Header().Set("Content-Type", "Application/json; charset=UTF-8")
	app.enableCors(w, r)
	json.NewEncoder(w).Encode(m)

}
func (app *Application) DeletePet(w http.ResponseWriter, r *http.Request) {

	// Enable CORS
	if r.Method == "OPTIONS" {
		app.enableCors(w, r)
		w.WriteHeader(http.StatusOK)
		return
	}
	// Get id from incoming url
	id := mux.Vars(r)["id"]

	// Delete Pets by id
	deleteResult, err := app.pets.Delete(r.Context(), id)
	if err != nil {
		app.serverError(w, err)
		return
	}

	app.infoLog.Printf("Have been eliminated %d pet(s)", deleteResult.DeletedCount)
	app.enableCors(w, r)
	w.Header().Set("Content-Type", "Application/json; charset=UTF-8")

}

func (app *Application) FindPetsByStatus(w http.ResponseWriter, r *http.Request) {

	if r.Method == "OPTIONS" {
		app.enableCors(w, r)
		w.WriteHeader(http.StatusOK)
		return
	}
	status_query := r.URL.Query().Get("status")
	app.infoLog.Printf("Endpoint Hit: FindPetsByStatus %s \n", status_query)

	var model []Pet
	status := strings.Split(status_query, ",")

	// Find Pets by status
	var err error
	model, err = app.pets.FindByStatus(r.Context(), status)
	if err != nil {
		// Use errors.Is to check for mongo.ErrNoDocuments
		if errors.Is(err, mongo.ErrNoDocuments) {
			app.infoLog.Println("Pets not found")
			w.WriteHeader(http.StatusNotFound)
			return
		}
		// Any other error will send an internal server error
		app.serverError(w, err)
		return
	}

	w.Header().Set("Content-Type", "Application/json; charset=UTF-8")
	app.enableCors(w, r)
	json.NewEncoder(w).Encode(model)

}

func (app *Application) FindPetsByTags(w http.ResponseWriter, r *http.Request) {

	if r.Method == "OPTIONS" {
		app.enableCors(w, r)
		w.WriteHeader(http.StatusOK)
		return
	}
	tag_query := r.URL.Query().Get("tags")
	app.infoLog.Printf("Endpoint Hit: FindPetsByTags %s \n", tag_query)

	var model []Pet
	tags := strings.Split(tag_query, ",")

	// Find Pets by tags
	var err error
	model, err = app.pets.FindByTags(r.Context(), tags)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			app.infoLog.Println("Pets not found")
			model = []Pet{} // Return empty array instead of null
		} else {
			// Any other error will send an internal server error
			app.serverError(w, err)
			return
		}
	}

	w.Header().Set("Content-Type", "Application/json; charset=UTF-8")
	app.enableCors(w, r)
	json.NewEncoder(w).Encode(model)

}

func (app *Application) GetPetById(w http.ResponseWriter, r *http.Request) {

	if r.Method == "OPTIONS" {
		app.enableCors(w, r)
		w.WriteHeader(http.StatusOK)
		return
	}
	// Get id from incoming url
	vars := mux.Vars(r)
	id := vars["petId"]

	app.infoLog.Printf("Get pet by id=%s \n", id)

	// Find Pets by id
	model, err := app.pets.FindByID(r.Context(), id)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			app.infoLog.Println("Pets not found")
			w.WriteHeader(http.StatusNotFound)
			return
		}
		// Any other error will send an internal server error
		app.serverError(w, err)
		return
	}

	w.Header().Set("Content-Type", "Application/json; charset=UTF-8")
	app.enableCors(w, r)
	if reflect.ValueOf(model).IsZero() {
		w.WriteHeader(http.StatusNotFound)
	} else {
		json.NewEncoder(w).Encode(model)
		w.WriteHeader(http.StatusOK)
	}

}

func (app *Application) UpdatePet(w http.ResponseWriter, r *http.Request) {

	if r.Method == "OPTIONS" {
		app.enableCors(w, r)
		w.WriteHeader(http.StatusOK)
		return
	}
	// Define Pets model
	var m Pet
	// Get request information
	err := json.NewDecoder(r.Body).Decode(&m)
	if err != nil {
		app.serverError(w, err)
		return
	}

	//m.ID = bson.ObjectIdHex(id)

	// Update existing Pet
	updateResult, err := app.pets.Update(r.Context(), m)
	if err != nil {
		app.serverError(w, err)
		return
	}

	app.infoLog.Printf("Pet has been updated, upserted_id=%v \n", updateResult.UpsertedID)

	w.Header().Set("Content-Type", "Application/json; charset=UTF-8")
	app.enableCors(w, r)
	json.NewEncoder(w).Encode(m)
	w.WriteHeader(http.StatusOK)
}

func (app *Application) UpdatePetWithForm(w http.ResponseWriter, r *http.Request) {
	if r.Method == "OPTIONS" {
		app.enableCors(w, r)
		w.WriteHeader(http.StatusOK)
		return
	}
	w.Header().Set("Content-Type", "Application/json; charset=UTF-8")
	app.enableCors(w, r)
	w.WriteHeader(http.StatusOK)
}

func (app *Application) UploadFile(w http.ResponseWriter, r *http.Request) {
	if r.Method == "OPTIONS" {
		app.enableCors(w, r)
		w.WriteHeader(http.StatusOK)
		return
	}
	w.Header().Set("Content-Type", "Application/json; charset=UTF-8")
	app.enableCors(w, r)
	w.WriteHeader(http.StatusOK)
}
