version: '3.8'

volumes:
  data: {}


networks:
  petstore-net:
    driver: bridge 


services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env

    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:mongo

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)


  mongo:
    image: mongo    
    restart: unless-stopped
    volumes:
      - data:/data/db
     
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
    ports:
      - 27017:27017
    networks:
      - petstore-net
   
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
    networks:
      - petstore-net

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward REDIS locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  